backend:
  name: gitlab
  repo: "tsp-c-devops/gtoxperience-project"
  branch: "feature/decap_cms"
  auth_type: "pkce"
  app_id: "a1a4da886c9b40043aff72393cd53d398e5c7659964deefb4150e2880df26cdf"
  api_root: "https://gitlab.cgi-berlin.cloud/api/v4"
  base_url: "https://gitlab.cgi-berlin.cloud"
  use_proxy_url: true 
  

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "intro"
    label: "Introduction Sections"
    folder: "data/intro"
    create: false
    delete: false
    files:
      - label: "AI and Automation Intro"
        name: "ai-and-automation"
        file: "data/intro/test.yaml"
        fields:
          - {label: "Title 1", name: "title1", widget: "text"}
          - {label: "Title 2", name: "title2", widget: "text"}
         